import Foundation

public enum ViolationType: String, Decodable {
    case firearms = "FIREARMS"
    case weapon = "WEAPON"
    case alcohol = "ALCOHOL"
    case tobacco = "TOBACCO"
    case meanderingApparatus = "MEANDERING_APPARATUS"
    case food = "FOOD"
    case useFirearms = "USE_FIREARMS"
    case useWeapon = "USE_WEAPON"
    case drinkingAlcohol = "DRINKING_ALCOHOL"
    case useTobacco = "USE_TOBACCO"
    case useMeanderingApparatus = "USE_MEANDERING_APPARATUS"
    case eatFood = "EAT_FOOD"
    case managerGuidance = "MANAGER_GUIDANCE"
    case time = "TIME"
    case outing = "OUTING"
    case overnightStay = "OVERNIGHT_STAY"
    case damageOfGoods = "DAMAGE_OF_GOODS"
    case theft = "THEFT"
    case chantage = "CHANTAGE"
    case disturbingSleep = "DISTURBING_SLEEP"
    case electronicDevice = "ELECTRONIC_DEVICE"
    case loud = "LOUD"
    case incorrectEntry = "INCORRECT_ENTRY"
    case laundry = "LAUNDRY"
    case violationOfTheUseOfFacilities = "VIOLATION_OF_THE_USE_OF_FACILITIES"
    case damageOfPost = "DAMAGE_OF_POST"
    case possessionOfElectronicsDevices = "POSSESSION_OF_ELECTRONICS_DEVICES"
    case cleanCounditionBad = "CLEAN_COUNDITION_BAD"
    case environmentPollution = "ENVIRONMENT_POLLUTION"
    case affectionateAct = "AFFECTIONATE_ACT"
    case sexualAct = "SEXUAL_ACT"
    case entryToProhibitedAreas = "ENTRY_TO_PROHIBITED_AREAS"
    case violationOfStudyRoomRules = "VIOLATION_OF_STUDY_ROOM_RULES"
    case outsiderEntry = "OUTSIDER_ENTRY"
    case none = ""
}
